# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: required
language: node_js
node_js:
    - "8"
stages:
  - test
  - build
  - name: deploy
    if: branch = master

cache: npm

services:
  - docker

# branches:
#   only:
#     - master            # only run CI on the master branch
#     - /^PR /            # also build pull requests

before_install:
  - cd web
  - npm install

jobs:
  include:
    # TODO: unit testing
    - stage: test
      script:
        - npm run lint
    #     - npm run test-ci

    - stage: build
      script:
        - docker build -t g0vhk/addressparser .

    - stage: deploy
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push g0vhk/addressparser

# TODO: trigger k8s deployment
#after_success:
