# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: required
language: node_js
node_js:
    - "8"

services:
  - docker

branches:
  only:
    - master            # only run CI on the master branch
    - /^PR /            # also build pull requests

before_install:
  - cd web
  - npm install

lint:
script:
  - npm run lint
  - npm run build
  - npm run test-ci

# TODO: push docker image
# TODO: trigger k8s deployment
#after_success:
