# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: required
language: node_js
node_js:
    - "8"
stages:
  - test
  # Build the docker image only on master branch
  - name: deploy
    if: branch = master

env:
  global:
    - REPO=addressparser
    - ORG=g0vhk


cache: npm

services:
  - docker

# branches:
#   only:
#     - master            # only run CI on the master branch
#     - /^PR /            # also build pull requests

before_install:
  - cd web
  - npm install

jobs:
  include:

    - stage: deploy
      script:
        - echo "VUE_APP_GA_TRACKING_ID=$GA_TRACKING_ID" >> .env
        - npm run build
        - if [[ ! -z "$DOMAIN" ]]; then echo $DOMAIN >> dist/CNAME; fi

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: web/dist # the local dir is relative to root and ignoring the one set with before_install
        on:
          branch: master
